### ISSUE TITLE
Allow timezone specification for UseDates setting

### ISSUE THREAD

**Issue by ethack** [ocmdev/rita#112]
When UseDates is set, it seems that Rita chooses or assumes a timezone which to split the datasets on.

A TimeZone config value would be useful to allow localization.

**Comment by Zalgo2462** [comment]
Hello, I was wondering if you could add some more information to your feature request. For instance, could you phrase it as a user story? 
I am wondering if it would be better to read the timezone data from the system? Additionally, I am wondering what the expected behavior would be if the timezone switched (whether a person moves, or the data is read by a system in a different timezone).
Quite a few changes will need to be made in order to support timezones, so I would like to gather as much information as possible on what the expected outcomes are for the feature.

Thank you!

**Comment by ethack** [comment]
Yep! This is more of a nice to have feature and may not be worth the effort in rita if the effort is too large. But on the off chance it was simply a change to a parameter in some go time conversion function, I thought it worth mentioning.

The user collects 2 days (48 hours) worth of logs in New York. Bro either rotates logs hourly or not at all. (Because if they are rotated daily then an easier solution would be to map each day's worth to a different database yourself. You could do this with hourly data but that would be tedious.) The data capture starts at 0:00 July 1 and ends at 23:59 July 3 EST.

The bro logs are then transferred to a location in California (PST) for analysis. The analyst sets UseDates to true in the rita config and imports the data. The expected result is that 2 databases would be created each containing 24 hours worth of data.
* 2017-07-01
* 2017-07-02

The actual result I don't know since I don't know how rita chooses the timezone to split on currently. My best guess is it uses the system timezone which would be PST in this example. So the result then would be 3 databases.
* 2017-06-30 
* 2017-07-01
* 2017-07-02
Where the first database has 3 hours worth of data, the second has 24 hours, and the third, 21 hours.

If rita does indeed use the system timezone, then a workable solution for my use case is to change the system timezone. The resolution would then be to document rita's behavior regarding timezones and the UseDates option and ideally provide guidance with an example command that switches the timezone on the system.

If rita is somehow gleaning timezone info from the log data then all I'd want is a modification to the comment in the default config above UseDates explaining the dates are split based on the the timezone found in the data.

I really should have started by asking how rita currently handles this.

**Comment by Zalgo2462** [comment]
Bro will record timestamps in unix format (utc seconds from the unix epoch). RITA splits these entries into dates based on UTC, such that the results from import are deterministic. While this is unfortunate in that unless you live in Greenwich, the dates that come out of RITA will not match your local dates, it does ensure that RITA will produce the same output on every machine throughout the world.

The timezone information is not available in the bro logs to my best knowledge.

**Comment by ethack** [comment]
I experienced different behavior.  The following 2 timestamps were the last connection timestamp and first connection timestamp, respectively, available in the `conn` database in 2 differently dated databases when I imported data using the `UseDates` setting.

Epoch date | Human readable date (GMT)
-- | --
1487228399 | 2017-02-16 06:59:59
1487228400 | 2017-02-16 07:00:00

1487228400 is February 16, 2017 00:00:00 (am) in MST which is what the machine running the import was set to.

**Comment by Zalgo2462** [comment]
Okay.... !!! I will dig into this! That means that Go is doing things without us asking. My best guess is that it is using the system tz. O.o

**Comment by Zalgo2462** [comment]
So right now, it looks like the code is using the system timezone to figure out date bounds. 

func Unix

func Unix(sec int64, nsec int64) Time

Unix returns the local Time corresponding to the given Unix time, sec seconds and nsec nanoseconds since January 1, 1970 UTC. It is valid to pass nsec outside the range [0, 999999999]. Not all sec values have a corresponding time value. One such value is 1<<63-1 (the largest int64 value).
