### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by jasonericreed** [ocmdev/rita#149]
I have been trying to install on a fresh image of Ubuntu 14.04 LTS. I am following the directions below. Errors in **BOLD**

-------------------------------------------------
Clone the package: git clone https://github.com/ocmdev/rita.git
Change into the source directory: cd rita
Make the installer executable: chmod +x install.sh
Run the installer: sudo ./install.sh
   - **e: Unable to locate package bro"**

I assume this is because I do not have bro installed? Anyone have tips for install of Bro? Does it need to be installed first? I have been trying to install it for 3 days and it never works.

**Comment by jasonericreed** [comment]
So i reinstalled using the Security onion  ISO. It is installed fine, but how do yo import and analyze? I have followed the directions and nothing ever shows up.

**Comment by carrohan** [comment]
Are you using the config file to map to your logs?

**Comment by ethack** [comment]
Hello @jasonericreed, 

I haven't tested it with vanilla 14.04 but it sounds to me that Ubuntu 14.04 doesn't have a `bro` package available in their package repos.  There is one available in the Security Onion distro and Ubuntu 16.04 which is why those installs work.

For importing and analyzing you can refer to this section of the readme which should hopefully get you started.
https://github.com/ocmdev/rita/blob/master/Readme.md#getting-started

If you have any more questions let us know.
